### PR TITLE
Add support of ruby 3.1 

### PR DESCRIPTION
**Pull request by taleh007**

### CODE REVIEW

**Comment by taleh007** [comment]
@CamJN Could you please verify it?

**Comment by taleh007** [comment]
@CamJN it would be awesome if u able to merge it soon :)

**Comment by taleh007** [comment]
Or maybe I pinged wrong maintainer. @Theaxiom could you please review PR?

**Comment by CamJN** [comment]
You're missing `image/ruby-3.1.0.sh`

**Comment by taleh007** [comment]
> You're missing `image/ruby-3.1.0.sh`

Wrong directory :( Done

**Comment by taleh007** [comment]
@CamJN could u check it, please?

**Comment by taleh007** [comment]
@CamJN @Theaxiom  could u please merge it, we just waiting to use it in production

**Comment by CamJN** [comment]
When you make a pull request, you can save yourself having to make so many changes by running `make build_all` to check if your changes work. Anyway, the permissions on `ruby-3.1.0.sh` are missing the execute bit, and the makefile needs the version bumped, i've fixed that locally and built the images, so with those changes i can merge the PR.

**Comment by taleh007** [comment]
@CamJN  All fixed and works.

**Comment by CamJN** [comment]
Thanks, I've been busy so I appreciate the legwork.

**Comment by mathieujobin** [comment]
Anyone tried to enable --yjit flag on ruby 3.1?
That would be great if Phusion Passenger Docker had that built-in

**Comment by taleh007** [comment]
https://github.com/ruby/ruby/blob/master/doc/yjit/yjit.md -- based on disclaimer I dont think it will be great to build-in it

**Pull request merged**
