### PR TITLE
Upgrade to Ruby 2.4.2

### PR DESCRIPTION
**Pull request by neilbartley**
Bump Ruby version to [2.4.2](https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-4-2-released/).

### CODE REVIEW

**Comment by OpakAlex** [comment]
@neilbartley can we merge && release this?

**Comment by neilbartley** [comment]
@OpakAlex afraid that'd be up to the maintainers, but thats certainly the aim.

**Comment by v3rron** [comment]
We should probably tag @OnixGH on that.

**Comment by OnixGH** [comment]
Hi! We usually pass by when there's a new Passenger release (which is soon) :)

**Comment by v3rron** [comment]
@OnixGH thank you :)

**Pull request merged**
