### PR TITLE
adding ruby 2.3

### PR DESCRIPTION
**Pull request by rwilsonncsa**
I wanted to use passenger-docker with ruby-2.3, so added ruby-2.3.

My only known issue is in image/nginx-passenger.sh, there was no ruby-2.2 section. I added it as well as a ruby-2.3 section.

### CODE REVIEW

**Comment by pinglamb** [comment]
+1

**Comment by yann** [comment]
:+1:

**Comment by alotofnoodles** [comment]
+1

**Comment by joe11051105** [comment]
👍

**Comment by Locke23rus** [comment]
:+1:

**Comment by ditsara** [comment]
👍

**Comment by antoinefinkelstein** [comment]
👍

**Comment by zywy** [comment]
+1

**Comment by chibacityblues** [comment]
+1

**Comment by rwilsonncsa** [comment]
Seems 2.3 has been added, so this gone.

**Pull request closed without merging**
