### PR TITLE
Update to Ruby 2.4.1

### PR DESCRIPTION
**Pull request by edwardmp**

### CODE REVIEW

**Comment by OnixGH** [comment]
Thanks :)

**Comment by edwardmp** [comment]
@OnixGH 
I have to say that this needs additional testing. I assumed the /pd_build/ruby-2.4.1.sh PD file is probably already generated somewhere else (couldn't find the pd_build folder in this repo).

**Comment by OnixGH** [comment]
Yeah, I know, I figured it'd be faster to just do it myself since the Changelog needed an edit too ;)

For future reference, it's in the same folder as the install.sh (it just gets copied first).

**Comment by edwardmp** [comment]
@OnixGH when do you expect a new release?

**Comment by OnixGH** [comment]
I'm thinking somewhere this or next week.

**Pull request merged**
