### PR TITLE
Upgrade Rubies to 2.2.9 / 2.3.6 / 2.4.3 and add 2.5.0

### PR DESCRIPTION
**Pull request by ledermann**
Upgrade to latest Rubies:

- [2.2.9](https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-2-9-released/)
- [2.3.6](https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-3-6-released/)
- [2.4.3](https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-4-3-released/)

### CODE REVIEW

**Comment by skunkworker** [comment]
@ledermann what about Ruby-2.5.0?

**Comment by skunkworker** [comment]
@ledermann awesome, thanks.

**Comment by skunkworker** [comment]
I guess with the [fixes to Passenger in version 5.2.0 with regards to Ruby2.5.0](https://blog.phusion.nl/2018/01/29/passenger-5-2-0/) this should be good to go now.

**Comment by jspooner** [comment]
I built the **ledermann:upgrade-rubies-2017-12-14** branch and tested with Ruby 2.5.  Everything looked good.

**Comment by OnixGH** [comment]
Thanks! I also updated the [changelog](https://github.com/phusion/passenger-docker/commit/244ec5d8efe7a43ec3319b348228004314275a5e).

**Pull request merged**
